Item (name, item_code, item_name)
Material Request (name, material_request_type, transaction_date, status)
Material Request Item (name, item_code, qty, parent)
Supplier (name, supplier_name, supplier_group)
Supplier Group (name)
Request for Quotation (name, transaction_date, status)
Request for Quotation Item (name, item_code, qty, parent)
Supplier Quotation (name, supplier, transaction_date, valid_till)
Supplier Quotation Item (name, item_code, qty, rate, parent)
Purchase Order (name, supplier, transaction_date, status)
Purchase Order Item (name, item_code, qty, rate, parent)
Purchase Receipt (name, supplier, posting_date, status)
Purchase Receipt Item (name, item_code, qty, parent)
Purchase Invoice (name, supplier, posting_date, status)
Purchase Invoice Item (name, item_code, qty, rate, parent)
Payment Entry (name, party_type, party, posting_date, paid_amount, reference_no)
Payment Entry Reference (name, reference_doctype, reference_name, allocated_amount, parent)
GL Entry (name, account, debit, credit, voucher_type, voucher_no)
Account (name, account_name, account_type)